# Generated by Django 4.0.6 on 2022-08-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasdeemprego',
            name='cbEscolaridade',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vagasdeemprego',
            name='cbFaixaSalarial',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vagasdeemprego',
            name='nameJob',
            field=models.CharField(max_length=100),
        ),
    ]
