# Generated by Django 4.0.6 on 2022-08-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0002_alter_vagasdeemprego_cbescolaridade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='createVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='vagasDeEmprego',
            new_name='vagaDeEmprego',
        ),
    ]
