# Generated by Django 4.0.6 on 2022-08-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0003_createvaga_rename_vagasdeemprego_vagadeemprego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createVaga',
        ),
    ]
