# Generated by Django 4.0.4 on 2022-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0004_delete_createvaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagadeemprego',
            name='cbEscolaridade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vagadeemprego',
            name='cbFaixaSalarial',
            field=models.CharField(max_length=100),
        ),
    ]
