# Generated by Django 4.0.6 on 2022-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0005_alter_vagadeemprego_cbescolaridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagadeemprego',
            name='nameJob',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
