# Generated by Django 4.0.6 on 2022-09-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0010_alter_vagadeemprego_cbfaixasalarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagadeemprego',
            name='cbFaixaSalarial',
            field=models.CharField(blank=True, choices=[('r', 'R$1.000'), ('r', 'R$1.000 a R$2.000'), ('r', 'R$2.000 a R$3.000'), ('r', 'Acima de R$3.000')], max_length=200),
        ),
    ]
