# Generated by Django 4.0.6 on 2022-09-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0017_faixasalarialchoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaixaSalarialChoice',
        ),
    ]
