# Generated by Django 4.0.6 on 2022-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0018_delete_faixasalarialchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaSalarialChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
