# Generated by Django 4.0.6 on 2022-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0019_faixasalarialchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixasalarialchoice',
            name='cbFaixaSalarial',
            field=models.CharField(choices=[('r', 'R$1.000'), ('r', 'R$1.000 a R$2.000'), ('r', 'R$2.000 a R$3.000'), ('r', 'Acima de R$3.000')], max_length=25, null=True, unique=True),
        ),
    ]
