# Generated by Django 4.0.6 on 2022-09-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0022_alter_faixasalarialchoice_cbfaixasalarial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faixasalarialchoice',
            old_name='cbFaixaSalarial',
            new_name='createVaga',
        ),
    ]
