# Generated by Django 4.0.6 on 2022-09-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0023_rename_cbfaixasalarial_faixasalarialchoice_createvaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faixasalarialchoice',
            old_name='createVaga',
            new_name='cbFaixaSalarial',
        ),
    ]
