# Generated by Django 4.0.6 on 2022-09-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobconvo', '0025_alter_faixasalarialchoice_cbfaixasalarial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faixasalarialchoice',
            table='cbFaixaSalarial',
        ),
    ]
